### ISSUE TITLE
Random inrfared values received from TSOP4838

### ISSUE THREAD

**Issue by 0xC0DEBA5E** [emc2cube/MySWeMosIRShield#2]
I get a lot of random readings when I connect the TSOP4838 to my board. 

Maybe it's because the pin of the blue LED on the board of the ESP8266 is the same the data pin of the TSOP4838 is connected to (D4).

I might have to mention that I didn't solder C1 onto the board, because I don't use the MySensors Board. So I'm not shure wether this comes from ripples in the supply voltage or if it is noise from the LED or something like that.

I removed the TSOP4838 and the random values were gone. 

If I pull down D4 (with a wire to GND), the LED lights up and if i open/close the connection between D4 and GND, random values are received again.

According to the [WEMOS Wiki](https://wiki.wemos.cc/products:d1:d1_mini) the pin D4 is connected to the internal LED.

If this pin is used as output to set the internal LED, it probably shouldn't be used as input for the readings from the TSOP4838.

So my question is:

Is the data pin D4 on your board also connected to the internal LED of your ESP8266? The board from the pictures in README.md looks a little bit different than mine.

**Comment by emc2cube** [comment]
Yes my board also have D4 connected to the internal LED. No issues on my side (but nothing in my program call for any blinking)

You may want to try to upload this to your wemos, changing the pin to D4, and see if with a simple program you have the same issue?
https://github.com/crankyoldgit/IRremoteESP8266/blob/master/examples/IRrecvDumpV2/IRrecvDumpV2.ino

Else maybe some defects on the board, honestly not idea.

**Comment by 0xC0DEBA5E** [comment]
My TSOP4838 was broken. I used another one and the problems were gone. I also tested other input pins with the broken TSOP4838 and got the same result. With the new one everything seems to work like it should. 

Thank you very much for your help. I will close this issue now. But one should keep in mind, that blinking the internal LED will possibly break IR-Receiver functionality.
